flosse/sloc

- CHANGELOG.md
- README.markdown
- spec/languages.coffee
- src/sloc.coffee
Objective-C = `.m`
Objective-C++ `.mm`
Both use:
Single line: `//`
Block: `/* */`
> Support for Objective-C and Objective-C++

- spec/languages.coffee
- src/sloc.coffee
Google Apps Script uses .gs as an extention for JavaScript files. Adding .gs as an alias for .js.
> Adding support for Google Apps Script's JavaScript extension (.gs)

- src/cli.coffee
Adding an alias properly substituted the correct language parser, but there is still a file filter that used only the known list of extensions. Added any alias to the extension list.
> Fixing a small bug in the alias handling code

- README.markdown
The bullet list at the beginning of the README had the items listed in a different order than how they appear in the actual results. Also, in the "supported outputs" section, it wasn't clear that there is a default output type in the terminal (not CLI-table). I hope that makes sense.
> Correction to readme to reflect proper order for result items

- README.markdown
- src/sloc.coffee
We treat `.iced` files the same way we treat `.coffee` files. Iced-coffee-script is just coffee-script with 2 additional keywords.
Please merge, I would like to have iced supported.
> add support for iced-coffee-script

- README.markdown
- spec/languages.coffee
- src/sloc.coffee
Most assemblers support `;` as a comment marker, but multiline comments are far from standardised. Some assemblers (notably, nasm) don't support them at all as far as I can tell. This is to enable at least support for counting lines in assembly files using the standard `;` comment marker.
> Add asm support

- README.markdown
- spec/languages.coffee
- spec/sloc.spec.coffee
- src/sloc.coffee
What still doesn't work is a hashtag in a string like `code "words # more"`. This still matches as 'mixed', but that's another issue...
**edit:** Caveat: When a comment starts with `#{` it is ignored. This can happen when commenting out an object literal, but this is an edge case, while interpolation is not.
> fix #48: don't count interpolated strings in coffeescript as comments 

- src/sloc.coffee
The Brightscript is the language created by Roku to allow create channels for their streaming devices:
https://sdkdocs.roku.com/display/sdkdoc/BrightScript+Language+Reference
It's a type of VisualBasic
> Adding support for Brightscript

- src/cli.coffee
- fixes error "(libuv) kqueue(): Too many open files in system"
- resolves #83
> fix: too many files in system cli error

- README.md
- spec/sloc.spec.coffee
- src/formatters/simple.coffee
- src/i18n.coffee
- src/sloc.coffee
Now reports the number of empty lines with block comments.
Goes from 
```
---------- Result ------------
Physical :  333
Source :  262
Comment :  39
Single-line comment :  35
Block comment :  4
Mixed :  25
Empty :  57
To Do :  1
Number of files read :  1
------------------------------
```
to
```
---------- Result ------------
Physical :  333
Source :  262
Comment :  39
Single-line comment :  35
Block comment :  4
Mixed :  25
Empty block comment :  0
Empty :  57
To Do :  1
Number of files read :  1
----------------------------
```
Closes #90
> "Fix" for Consistency check #90

- README.md
- src/sloc.coffee
Add [LilyPond](http://lilypond.org/) support. Lilypond uses single `%` for comments and `%{` and `%}` to start and stop block comments, respectively.
> Add Lilypond support

- src/sloc.coffee
fix for LaTeX regex: latex uses a single `%` for comments, not `%%`.
> fix for LaTeX regex

- README.md
- spec/languages.coffee
- src/sloc.coffee
Adding support for Agda, a dependently typed functional programming language and proof assistant.
Same syntax as Haskell regarding sloc.
> Add Agda support in sloc

- README.md
- src/cli.coffee
Simple tweak to support an --include flag, for scenarios where it's preferable to define a regex for files to include rather than exclude.
(In some cases it can be extremely difficult, if not impossible, to define a negative regexp in order to achieve inclusion via clever exclusion.)
> support include flag

- README.md
- spec/languages.coffee
- src/sloc.coffee
Adds support for [Ren'Py](https://renpy.org), a Python-based visual novel engine. Syntax is identical to Python regarding sloc.
Adds a separate module export for `rpy` to note Ren'Py DSL statements which support inline comments. Also removes an illegal `;` from the Python spec.
> Add Ren'Py support in sloc

- .travis.yml
- package.json
- src/sloc.coffee
closes #123 (since it has merge issues)
updated to current + LTS versions
see https://nodejs.org/en/about/releases/
Updated all dependencies to the latest version. Except `istanbul` and `readdirp`. Istanbul was deprecated and the new version is called  NYC. I didn't swap it out as I cannot see it being used anywhere. ReadDirP was updated to the newest 2.x version. It wasn't updated to 3.x because the callback API was deprecated. A separate pull request to update the code to use promises or streams is needed.
Wrapped a line because the linter was complaining. 
two tests fail, but they seem to fail in master aswell
`      2) should support agda`
`      1) should support rpy`
travis fails #127 due to the two errors above
> Update Everything (almost)

- README.md
- src/sloc.coffee
Jade was renamed to pug and so was the file extension from .jade to .pug 
This pull request adds the pug file extension while keeping the jade extension for backwards compatibility
> Add pug file support

- src/cli.coffee
The current version of readdirp in the codebase is 3.3.0. 
However, due to a series of breaking changes readdirp introduced during the transition from version 2.x to 3.x, current implementation does not function as expected when running on directories. However it still works when running on single files. In this PR i aim to restored the functionality.
Example:
```
sloc cli.js ../lib
/Users/domen/.nvm/versions/node/v20.10.0/lib/node_modules/sloc/node_modules/readdirp/index.js:264
throw new TypeError('readdirp: root argument must be a string. Usage: readdirp(root, options)');
^
TypeError: readdirp: root argument must be a string. Usage: readdirp(root, options)
at readdirp (/Users/domen/.nvm/versions/node/v20.10.0/lib/node_modules/sloc/node_modules/readdirp/index.js:264:11)
at readDir …
```
> SLOC: make it work on directories

- spec/languages.coffee
- src/sloc.coffee
Referenced from https://ziglang.org/documentation/master/#Comments
Zig has three comment types all single line (`//` , `///` , `//!`). We can just consider the `//` case as it catches the other two. There are no multiline comments.
I have alphabetized a couple of extensions.
> Add support for the Zig programming language

- README.md
- package-lock.json
- spec/languages.coffee
- src/sloc.coffee
VHDL, Verilog, and SystemVerilog are popular Hardware Description Languages for describing FPGAs and ASICs. This PR adds support for them to SLOC, as well as unit tests to verify that SLOC is counting lines correctly.
I've taken the liberty of adding a package-lock file as well- [these files should be committed and tracked in the git index](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json?v=true#description), per NPM's recommendation. This helps to ensure checkouts on different machines have the same dependency tree.
> Add support for VHDL, Verilog, SystemVerilog
